# Generated by Django 5.2.6 on 2025-10-19 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fechaHora']},
        ),
        migrations.AddField(
            model_name='cita',
            name='medico_especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='api.medicoespecialidad'),
        ),
        migrations.AlterField(
            model_name='medicoespecialidad',
            name='box',
            field=models.CharField(default='Sin asignar', max_length=50),
        ),
    ]
