# Generated by Django 5.2.6 on 2025-11-08 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviada', 'Enviada'), ('Fallida', 'Fallida'), ('Completada', 'Completada')], default='Pendiente', max_length=10),
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorio', to='api.cita')),
            ],
            options={
                'ordering': ['fecha_programada'],
            },
        ),
    ]
