# Generated by Django 5.2.6 on 2025-10-19 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cita_options_cita_medico_especialidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='api.medico')),
            ],
            options={
                'unique_together': {('medico', 'nombre')},
            },
        ),
        migrations.AlterField(
            model_name='medicoespecialidad',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medico_especialidades', to='api.box'),
        ),
    ]
