# Generated by Django 5.2.6 on 2025-10-19 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_box_alter_medicoespecialidad_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='medicoespecialidad',
            name='box',
        ),
        migrations.AddField(
            model_name='horario',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='api.box'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
